
# *ABSTRACT* {-}

Soil transmitted helminths (STH), i.e., geohelminths, are parasitic intestinal worms that cause intestinal nematode infections (INI).  According to the Lancet's 2019 global burden of disease study INI - comprising *ascariasis*, *trichuriasis*, and *hookworm disease* - are the most prevalent of the neglected tropical diseases.  Additionally, INI are the second most burdensome neglected tropical diseases, after dengue.

\vspace{10pt}

An experts' hypothesis of geohelminths infections prevalence is that one or more WaSH (water, sanitation, and hygiene) variables impact prevalence rates.  This project investigates whether one or more WaSH variables are geohelminths infections prevalence risk factors.  The investigation is via Binomial geostatistical logistic models.

\vspace{10pt}

The resulting model suggests that a non-linear, statistically significant, association exists between *piped sewage facilities access* and *Hookworm disease infections prevalence*.  It suggests that, as the percentage of inhabitants that have access to piped sewage facilities increases from $0$ to approximately $24\%$, *Hookworm disease* prevalence odds decline.  However, beyond the $24\%$ point *Hookworm disease* prevalence odds start increasing with increasing access percentage.  The increasing prevalence odds after this$24\%$ [inflection] point might be due to a mix of *access density* & *poor maintenance*.  The piped sewage facilities access percentage is the percentage of an area’s inhabitants that have access to piped sewage facilities. The measure does not give an insight into access density, i.e., the median number of people per piped [defaecation] facility. Defaecation facilities that have high access densities might not be well-maintained.