
# *DISCUSSION* \label{chapter:discussion}

This project studies the association between WaSH variables and geohelminths infections prevalence.  It especially focuses on *Hookwookworm* disease prevalence, and investigates whether one or more WaSH variables are geohelminths infections prevalence risk factors.  The investigation is via explanatory Binomial geostatistical logistic models.

\vspace{10pt}

The resulting model suggests that *piped sewage facilities access* is a statistically significant risk factor.  The model illustrates a non-linear relationship between *piped sewage facilities access* and *Hookworm disease infections prevalence*.  As the percentage of inhabitants that have access to piped sewage facilities increases from $0$ to approximately $`r round(-100*0.5*CPL/CPQ, digits = 2)`\%$ *Hookworm disease* prevalence odds decline.  However, beyond the $`r round(-100*0.5*CPL/CPQ, digits = 2)`\%$ access point *Hookworm disease* prevalence odds start increasing with increasing access percentage.

\vspace{10pt}

The increasing prevalence odds after the $`r round(-100*0.5*CPL/CPQ, digits = 2)`\%$ inflection point might be due to a mix of *access density* & *poor maintenance*.  The piped sewage facilities access percentage is the percentage of an area’s inhabitants that have access to piped sewage facilities. The measure does not give an insight into access density, i.e., the median number of people per piped [defaecation] facility. Defaecation facilities that have high access densities might not be well-maintained.

## Assumptions

\noindent The key/implicit assumptions:

> * The ESPEN (Expanded Special Project for Elimination Neglected Tropical Diseases) survey measures, when available, are error free.\newline
> * If an ESPEN record's *number of survey examinations* value is zero or null, then the examinations' data is missing.\newline
> * If an ESPEN record's *number of positive tests* value is null, then the positives test data is missing.\newline
> * The WaSH access percentage estimates, and the population density estimates, are approximately accurate.\newline


## Limitations

The assumptions hint at the project's limitations.  The data sets of a number of countries have [missing data cells](https://helminthiases.github.io/data/missing.html#missing-spatiotemporal-data); the critical missing data being geographic co&ouml;rdinates, year, the number of examinations, and the number of positive tests.  In the end, instead of a place agnostic model, the project's models use the data of a single country: Togo.  However, the model can be extended in the future.

\vspace{10pt}

It is quite possible that the accuracy of the WaSH access percentage estimates, and of the population density estimates, varies between and within countries.  Hence, the findings herein should be re-explored via one or more alternative estimates.


## Validity

\noindent Finally, the project's validity (@Trochim2006) can be understood via

> * **Internal Validity**: The project's focus is not the determination of a cause & effect relationship, hence an internal validity valuation is inapplicable.

> * **Construct Validity**: Each explanatory model determines **(a)** whether there is a statistically significant association between an extraneous independent variable and *Hookworm disease* infections prevalence, and subsequently **(b)** the variable's impact.  This is in line with the project's aim & objectives, i.e., the operational setting does reflect the construct.

> * **External Validity**: At present, the study's conclusions can be generalised to Togo only.

> * **Conclusion Validity**: Each of the resulting model's MCML (Monte Carlo Maximum Likelihood) coefficient estimates is statistically significant, additionally a different estimation method - Bayesian parameter estimation - produces similar estimates.  Hence, it is reasonable to conclude that $piped\underline{\hspace{0.1cm}}sewer$ is probably a risk factor. The case would be stronger in the case of a *temporal Binomial geostatistical logistic model*.
