---
title: Helminthiases
author: 36112985
site: bookdown::bookdown_site
bibliography: bibliography/bibliography.bib
biblio-style: siam
link-citations: yes
urlcolor: olive
linkcolor: brown
citecolor: orange
fontsize: 10pt
documentclass:
  - book
classoption:
  - fleqn
geometry:
  - letterpaper
  - twoside
  - hmargin = 0.85in
  - vmargin = 1.0in
output:
  bookdown::pdf_document2:
    keep_tex: FALSE
extra_dependencies:
  - booktabs
  - float
header-includes:
  - \usepackage{color}
  - \usepackage{caption}
  - \usepackage{bm}
  - \usepackage{booktabs}
  - \usepackage{xcolor}
  - \usepackage{titlesec}
  - \usepackage{tikz}
  - \usepackage{amsthm}
  - \usepackage{hyperref}
  - \usepackage[nameinlink, capitalize]{cleveref}
  - \usepackage[utf8]{inputenc}
  - \usepackage{ragged2e}
  - \usepackage{fancyhdr}
  - \usepackage{appendix}
  - \newtheorem{theorem}{Theorem}
  - \newtheorem{corollary}{Corollary}[theorem]
  - \newtheorem{proposition}{Proposition}[theorem]
  - \newtheorem{remark}{Remark}
  - \newtheorem{definition}{Definition}
  - \captionsetup[figure]{font={small, color=gray}, width=.8\linewidth}
  - \definecolor{darkgrey}{HTML}{4a4a4a}
  - \definecolor{duskyblue}{HTML}{6C779C}
  - \definecolor{wine}{rgb}{.44,.18,.21}
  - \usetikzlibrary {angles, quotes, graphs, arrows.meta, automata, positioning, shadows}
  - \creflabelformat{equation}{#2\textup{#1}#3}
  - \crefname{appsec}{appendix}{appendices}
  - \Crefname{appsec}{appendix}{appendices}
  - \renewcommand{\thesection}{\Roman{section}}
  - \renewcommand{\thesubsection}{\Alph{subsection}}
  - \renewcommand{\thesubsubsection}{\arabic{subsubsection}}
  - \renewcommand{\theparagraph}{\alph{paragraph}}
  - \renewcommand{\thesubparagraph}{\roman{subparagraph}}
  - \titleformat{\section}[block]{\normalfont\normalsize\scshape\center}{\thesection.}{1em}{}
  - \titleformat{\subsection}[block]{\normalfont\itshape\center}{\thesubsection.}{1em}{}
  - \titleformat{\subsubsection}{\normalfont}{\thesubsubsection.}{1em}{}
  - \titleformat{\paragraph}{\normalfont}{\theparagraph.}{1em}{}
  - \titleformat{\subparagraph}{\normalfont\small}{\thesubparagraph.}{1em}{}
  - \titlespacing{\subparagraph}{0pt}{10pt}{10pt}
  - \titlespacing{\section}{0pt}{35pt}{10pt}
  - \titlespacing{\subsection}{0pt}{25pt}{*1}
  - \setcounter{secnumdepth}{5}
  - \setcounter{tocdepth}{5}
---

\fancypagestyle{custompagestyle}{%
\fancyhf{}% Clear header/footer
\fancyhead[OC]{\uppercase{River Blindness}} % Title on Odd pages, center.
\fancyhead[OR]{\thepage}
\fancyhead[EC]{\uppercase{River Blindness}} % Title on Even page, center.
\fancyhead[EL]{\thepage}
\fancyfoot[O]{}
\fancyfoot[E]{}
\renewcommand{\headrulewidth}{0pt} % Removes header rule
}
\pagestyle{custompagestyle}

<!--- Global Settings --->
```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.table.format = 'latex')
options(knitr.kable.NA = '')
```


```{r include = FALSE}
library(xtable)
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)

library(magrittr)
library(latex2exp)
library(patchwork)
library(knitr)
library(kableExtra)

```

